version: '3.8'

services:
  backend:
    build: ./mern/Back-end-Integration  # Corrected path to the backend Dockerfile
    container_name: backend-app
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb+srv://workwithsuhel:erOMdtcMcn3BmHjS@application.wxs32.mongodb.net/app
      JWT_SECRET: 123144
      RAZORPAY_KEY_ID: rzp_test_cAa3gCF0eP8i4R
      RAZORPAY_KEY_SECRET: oXo3dmmWmWJhvg6AuEU6etJ7
    volumes:
      - ./mern/Back-end-Integration:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./mern/front-end-integration  # Adjust frontend path if needed
    container_name: frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    volumes:
      - ./mern/front-end-integration:/app
      - /app/node_modules
    restart: always

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"  
    volumes:
      - mongo-data:/data/db  
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"  
    

volumes:
  mongo-data:
