version: "3.8"

services:
  backend:
    image: back-end11:latest
    container_name: backend-app
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://admin:password@mongo:27017/app?authSource=admin
    volumes:
      - ./mern/Back-end-Integration:/app
    depends_on:
      - mongo
    networks:
      - mern_network
    restart: always
    expose:
      - "5000"

  frontend:
    image: front-end11:latest
    container_name: frontend-app
    environment:
      - REACT_APP_API_URL=http://backend:5000
    volumes:
      - ./mern/front-end-integration:/app
    depends_on:
      - backend
    networks:
      - mern_network
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mern_network
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - mern_network
    restart: always

networks:
  mern_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
