version: '3.8'

services:
  backend:
    build: ./mern/Back-end-Integration  # Corrected path to the backend Dockerfile
    container_name: backend-app
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/mydatabase
    volumes:
      - ./mern/Back-end-Integration:/app  # Mount backend code
      - /app/node_modules  # Prevents overwriting node_modules
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./mern/front-end-integration  # Adjust frontend path if needed
    container_name: frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    volumes:
      - ./mern/front-end-integration:/app
      - /app/node_modules
    restart: always


  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"  # Mongo Express UI runs on port 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: suhelkhan12
      ME_CONFIG_MONGODB_ADMINPASSWORD: 14557
      ME_CONFIG_MONGODB_URL: mongodb+srv://workwithsuhel:erOMdtcMcn3BmHjS@application.wxs32.mongodb.net/app

volumes:
  mongo-data:  # Persistent storage for MongoDB
