version: '3.8'

services:
  backend:
    build: ./mern/Back-end-Integration
    container_name: backend-app
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb+srv://workwithsuhel:erOMdtcMcn3BmHjS@application.wxs32.mongodb.net/app
      
    volumes:
      - ./mern/Back-end-Integration:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - mern_network
    restart: always

  frontend:
    build: ./mern/front-end-integration
    container_name: frontend-app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    volumes:
      - ./mern/front-end-integration:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - mern_network
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mern_network
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - mern_network
    restart: always

networks:
  mern_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
