apiVersion: v1
kind: Service
metadata:
  name: mern-service
  namespace: mern-namespace
  labels:
    app: mern-deploy
spec:
  selector:
    app: mern-deploy
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000 
  type: ClusterIP
