#For Testing push your own images and more 

name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (optional)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build . -f Dockerfile -t my-image-name:${{ github.run_id }}

      # Optional: Push the image to GitHub Container Registry
      # - name: Push Docker image
      #   run: |
      #     docker tag my-image-name:${{ github.run_id }} ghcr.io/${{ github.repository_owner }}/my-image-name:${{ github.run_id }}
      #     docker push ghcr.io/${{ github.repository_owner }}/my-image-name:${{ github.run_id }}
